services:
  app:
    build: .
    container_name: ecommerce_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb+srv://Youssef:fqxM72cGhyasXFxf@cluster0.p0jna.mongodb.net/
    env_file:
      - config.env

  redis:
    image: redis:7
    container_name: ecommerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data: